<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNOYKxZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNOYKxZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNOYKxZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNOYKxZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNNOYKxZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NNOYKxZ',
    'container.build_id' => '1965233a',
    'container.build_time' => 1627611167,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNOYKxZ');
