<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcrFk89\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcrFk89/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcrFk89.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcrFk89\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAcrFk89\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AcrFk89',
    'container.build_id' => '3713009a',
    'container.build_time' => 1627596590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcrFk89');
