<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_web_main_main' => [[], ['_controller' => 'App\\Controller\\Web\\MainController::main'], [], [['text', '/']], [], []],
    'app_api_product_postproduct' => [[], ['_controller' => 'App\\Controller\\Api\\ProductController::postProduct'], [], [['text', '/api/products']], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::addProduct'], [], [['text', '/api/products/add']], [], []],
    'show_product' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::showProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/products/show']], [], []],
    'show_available_products' => [[], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::availableProducts'], [], [['text', '/api/products/available']], [], []],
    'show_more_than_five_products' => [[], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::moreThanFiveProducts'], [], [['text', '/api/products/more-than-five']], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::deleteProduct'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/products/delete']], [], []],
    'update_product' => [['id', 'amount'], ['_controller' => 'App\\Controller\\Api\\ProductControllerOld::updateProduct'], [], [['variable', '/', '[^/]++', 'amount'], ['variable', '/', '[^/]++', 'id'], ['text', '/api/products/update']], [], []],
];
