version: '3'

services: #containers' list

  php:
    container_name: symfony_php
    build:
      context: ./docker/php
    volumes:
      - ./app/:/var/www/symfony/
    depends_on: #build database before php container
      - database
    networks:
      - symfony

  database:
    container_name: symfony_postgres
    image: postgres
    restart: always
    hostname: symfony_postgres
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgres
    networks:
      - symfony

  pgadmin:
    container_name: symfony_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5555:80"
    depends_on:
      - database
    links:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - symfony

  nginx:
    container_name: symfony_nginx
    image: nginx:stable-alpine
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - symfony

networks:
  symfony:

