<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCV3TV8y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCV3TV8y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCV3TV8y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCV3TV8y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCV3TV8y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CV3TV8y',
    'container.build_id' => '08a70da7',
    'container.build_time' => 1626422180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCV3TV8y');
