<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUvmK0T\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUvmK0T/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJUvmK0T.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJUvmK0T\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJUvmK0T\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JUvmK0T',
    'container.build_id' => 'c8b1798d',
    'container.build_time' => 1626417767,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUvmK0T');
